### ISSUE TITLE
vim.lsp.buf.formatting is deprecated. Use vim.lsp.buf.format { async = true } instead

### ISSUE THREAD

**Issue by flppv** [MunifTanjim/prettier.nvim#16]
Seeing this message with a selection of what to use for formatting (tsserver or null-ls) when I save the file with nvim(HEAD) configured exactly as in README.md from this repo. I'd create a PR with updated example config, if I would be more experienced :D

**Comment by MunifTanjim** [comment]
If you wanna update the README.md file, sure, go ahead. Or I can do it later.

**Comment by mustafaergul** [comment]
Couldn't achieve with `vim.lsp.buf.format { async = true }` as well :/

**Comment by MunifTanjim** [comment]
The README is updated by https://github.com/MunifTanjim/prettier.nvim/pull/19.
Try that to see if your problem resolves @mustafaergul .
