### ISSUE TITLE
.prettierrc

### ISSUE THREAD

**Issue by budchirp** [MunifTanjim/prettier.nvim#2]
Is that supports .prettierrc and other config files if it supports I should add this to README

**Comment by MunifTanjim** [comment]
If prettier supports it, this plugin supports it too. 😃

I guess we can add a line mentioning that with this link: https://prettier.io/docs/en/configuration.html

**Comment by budchirp** [comment]
Oh thanks!

**Comment by budchirp** [comment]
And I think adding the packer installation option would be good

**Comment by MunifTanjim** [comment]
Closed by #3
