### ISSUE TITLE
Had to globally install prettier before it worked

### ISSUE THREAD

**Issue by aziznal** [MunifTanjim/prettier.nvim#27]
Hello. I installed this plugin and and setup its config like in the readme. I then spent a bunch of time trying to get it to work with no use. I checked my config again and again and again.

In the end, what worked out for me was to install prettier using `npm install -g prettier`. Was this something obvious that I just missed or should it be added to the plugin docs perhaps? Am I missing something else that caused me to do this?

Thanks for the awesome plugin by the way :rocket:

**Comment by MunifTanjim** [comment]
`prettier` needs to be available in one of these places:
- In `./node_modules/.bin` folder, i.e. you've locally installed prettier for your project
- Anywhere in the `PATH` env variable.
  - That means, either you've installed `prettier` globally
  - Or installed it using something like [mason.nvim](https://github.com/williamboman/mason.nvim), that modifies the `PATH` env variable for Neovim.

This plugin does not install `prettier`. It only uses the already available `prettier` on your system/project.

**Comment by MunifTanjim** [comment]
Also, `prettier` would be pretty slow. It's recommended to use `prettierd`: https://github.com/fsouza/prettierd

**Comment by aziznal** [comment]
Gotcha. I come from the land of vs code where everything is sort of taken care of in the background which caused me some confusion. Appreciate your help!

**Comment by Devansh-Baghel** [comment]
@MunifTanjim I had the same problem and it got fixed after looking through this issue, it would be really helpful for newcomers if you could pin this issue and/or mention it in the readme.

**Comment by MunifTanjim** [comment]
- https://github.com/MunifTanjim/prettier.nvim/pull/28

Added in `README.md`. Also added warning message if prettier is not found during plugin setup.
