### ISSUE TITLE
Does not format if there is no .prettierrc present

### ISSUE THREAD

**Issue by uloco** [MunifTanjim/prettier.nvim#35]
When installed as the config described, vim.lsp.buf.format() does not format the current buffer if there is no .prettierrc founc and no prettier config value is present in the package.json.

Is this supposed to work like this? Installing prettier via mason and null-ls does not need a prettierrc to work.

**Comment by MunifTanjim** [comment]
Yes this is intentional. You can run `:Prettier` to manually format without needing any config file.

**Comment by uloco** [comment]
well ok then...
