### ISSUE TITLE
Not loading options?

### ISSUE THREAD

**Issue by omar2205** [MunifTanjim/prettier.nvim#5]
I have this config. When I format it doesn't format according to these options

![image](https://user-images.githubusercontent.com/1373867/149244849-9fb970eb-8d53-42d3-9e91-41d2e8ed4375.png)

**Comment by MunifTanjim** [comment]
It's working for me tho. By the way, if you set options this way, it will always override the options you set in your config file. So you might want to not set options in the `prettier.setup(...)` function and put a config file (e.g. `.prettierrc.json` or `.prettierrc.js`) in your project's root directory.

Also are you sure prettier is formatting your file? Can you try running the `:Prettier` command in neovim to see if that works?

**Comment by omar2205** [comment]
I copied the example in the readme. I have set a message to pop after formatting.

**Comment by MunifTanjim** [comment]
If you're also using `tsserver` or something similar, those might be handling the formatting. Check this: https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts

This is how I'm doing it in my config:

- https://github.com/MunifTanjim/dotfiles/blob/47a21021ab0d6aad909fbc5b6d3c7cf3199cdbe1/private_dot_config/nvim/lua/config/lsp/init.lua#L10-L13
- https://github.com/MunifTanjim/dotfiles/blob/47a21021ab0d6aad909fbc5b6d3c7cf3199cdbe1/private_dot_config/nvim/lua/config/lsp/init.lua#L88-L90
- https://github.com/MunifTanjim/dotfiles/blob/47a21021ab0d6aad909fbc5b6d3c7cf3199cdbe1/private_dot_config/nvim/lua/config/lsp/init.lua#L137
- https://github.com/MunifTanjim/dotfiles/blob/47a21021ab0d6aad909fbc5b6d3c7cf3199cdbe1/private_dot_config/nvim/lua/config/lsp/init.lua#L153
