### ISSUE TITLE
Prettier plugins (Lua)

### ISSUE THREAD

**Issue by CleoMenezesJr** [MunifTanjim/prettier.nvim#7]
I have the Lua plugin for Prettier installed, shouldn't just putting it in the filetypes list work?
![image](https://user-images.githubusercontent.com/54215258/178203701-84c9cc4e-ce56-43d2-93dd-1e58142aa75d.png)

**Comment by MunifTanjim** [comment]
Yes it should work. But it also depends on how you've set up your neovim lsp config.

What are you experiencing? What's not working? How do I reproduce it?

**Comment by CleoMenezesJr** [comment]
Sorry for bothering you. I went deeper to read the logs and realized that the problem is with the Prettier plugin

It's actually an issue that's been open for quite some time: https://github.com/prettier/plugin-lua/issues/20
