### ISSUE TITLE
Prettier plugins (vue)

### ISSUE THREAD

**Issue by doubled3264** [MunifTanjim/prettier.nvim#8]
I watch a new video from mr. Craftzdog / mr takuya and follow the step to set prettier on react and success..
But when i try to use volar or vuels on my lsp config..
And i use prettier or prettierd and add filetypes "vue" on prettier.setup() but no one work

**Comment by MunifTanjim** [comment]
- How have you set up your project?
- Do you have all the necessary packages installed?
- Does running `prettier -w /path/to/file.vue` format the file correctly?

**Comment by doubled3264** [comment]
i'm sorry, i have typo on null-rs setup
now formatter on .vue is work with :Prettier, thanks
