### ISSUE TITLE
Can't run on save as LSP

### ISSUE THREAD

**Issue by harmolipi** [MunifTanjim/prettier.nvim#9]
Hello, I'm trying to get set up to use your Prettier LSP but I can't seem to get it to work, despite I think using the same configuration. Right now, the only way I can get prettier set up is to configure null_ls' builtin: `null_ls.builtins.formatting.prettier` or. `null_ls.builtins.formatting.prettierd`.

That works, but with that I don't have the option to set some global prettier options, so I'd rather use yours where I can set them in my `prettier.rc.lua` config file. I installed the plugin, I set it up passing `bin`, `filetypes`, and some format options like `trailing_comma = "es5", single_quote = true`, and I also added `vim.cmd("autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()")` to my null_ls config for formatting on save.

But after all that, still it seems like nothing is happening when I save. I do have nvim-lspconfig installed and working. I'm not sure if it should appear in the list, but if I run `:LspInfo` I don't see prettier there. Also if I manually call `:lua vim.lsp.buf.formatting()` nothing happens. But if I run `prettier -w script.js` from the terminal, it does work.

I'm a little new to neovim, but I hope this makes sense - hopefully I'm just missing something obvious! Thank you!

**Comment by MunifTanjim** [comment]
> I'm not sure if it should appear in the list, but if I run :LspInfo I don't see prettier there

It won't be there. Try running `:NullLsInfo` to see if prettier is registered properly. It should be displayed as active source:

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/8050659/184222869-bc125a4b-1266-4953-a6b5-18ae40c95809.png">

btw, `prettier.nvim` will only be active if you have a prettier config file in your project directory.

---

You can also try running `:Prettier` command to see if that works. If the file is formatted correctly, it means the plugin is working... you just need to fix the format-on-save part.

One possibility is that you have multiple LSP servers that can format the file and the request is handled by some other LSP server (i.e. it's not reaching `null-ls` at all).

I looked a bit into your config. You might want to remove this part: https://github.com/harmolipi/dotfiles/blob/da71baaf80c06fc6ef8724643d8490e362b31321/nvim/plugin/lspconfig.rc.lua#L26-L33, since you want to use `null-ls` for format on save feature. Those lines are setting format on save for each LSP servers.

---

In case it helps, here's my config:

- [`~/.config/nvim/lua/config/lsp/formatting.lua`](https://github.com/MunifTanjim/dotfiles/blob/2bb2b602735e947eb677ee4dccacd096db143c08/private_dot_config/nvim/lua/config/lsp/formatting.lua): Here I define formatting functions that ignore `tsserver` and `jsonls` for formatting files, because I want them to be formatted by `prettier.nvim` via `null-ls`.
- [`~/.config.nvim/lua/config/plugins/lsp/null-ls.lua`](https://github.com/MunifTanjim/dotfiles/blob/2bb2b602735e947eb677ee4dccacd096db143c08/private_dot_config/nvim/lua/config/plugins/lsp/null-ls.lua#L19): Set up `null-ls` and format on save (using the function defined in the previous file, instead of `vim.lsp.buf.formatting`).

**Comment by harmolipi** [comment]
Oh thank you! Didn't know about `:NullLsInfo` but that made it much easier to track things down.

> btw, prettier.nvim will only be active if you have a prettier config file in your project directory.

This ended up being the key! I didn't realize that that was the case, and thought I could simply use my prettier.nvim configuration file for some general settings, rather than setting them in a `.prettierrc` file for each project (though I know that's the best practice). Once I added a basic prettier config file, I was able to see prettier.nvim in `:NullLsInfo`.

In that case, what's the relationship between the settings we pass to `.setup()` and those in `.prettierrc`? If I still wanted some global prettier options, could I just set them all in `.setup()` and then add a blank `.prettierrc` to the directory of my JS projects?

Also thanks for even looking into my configuration and sharing yours too - it makes sense that I probably don't need to format on save for my LSP servers, since null-ls is providing my formatters. I'll look into yours and see if I can clean mine up accordingly. Besides these small questions though, you can probably close this issue out. Thank you for the help and for your plugin!

**Comment by MunifTanjim** [comment]
> In that case, what's the relationship between the settings we pass to .setup() and those in .prettierrc? If I still wanted some global prettier options, could I just set them all in .setup() and then add a blank .prettierrc to the directory of my JS projects?

`prettier.nvim` will register with `null-ls` as part of lsp formatter only if you have a prettier config file (it can be blank).

But you can also use it without the lsp setup. Maybe you're editing a single file outside any projects... in that case you can run ``:Prettier` or set some keybindings in your config and use those:

```
" range_formatting in visual mode
xmap <Leader>f <Plug>(prettier-format)

" formatting in normal mode
nmap <Leader>f <Plug>(prettier-format)
```

---

~Currently the settings pass to `setup()` overrides anything in prettier config file. I think that behavior can be improved tho.~

~Maybe when config file is found, ignoring the settings passed to `setup()` would be a better idea?~ 🤔

Now these options are only used if prettier config file is not found and you run prettier with the `:Prettier` command or `<Plug>(prettier-format)` keybindings. This behavior can be changed with the `config_precedence` option.

**Comment by MunifTanjim** [comment]
Added `config_precedence` support: https://github.com/MunifTanjim/prettier.nvim/commit/b236ba05266bc006370bb69a0fbc296b2ca73c24

**Comment by harmolipi** [comment]
> Now these options are only used if prettier config file is not found and you run prettier with the :Prettier command or <Plug>(prettier-format) keybindings. This behavior can be changed with the config_precedence option.

Hey that makes sense, good call, thank you! And I'll definitely set some keybindings up so I can do it that way if I'm not in a project directory. Thanks!

**Comment by dlvhdr** [comment]
I'm also having this issue, running prettier on the cli works.
I even created a `.prettierrc` file just to use the extension as the project didn't come with one.
I see it registered in `NullLsInfo` but running `:Prettier` or `:lua vim.lsp.buf.formatting()` does nothing :(

https://user-images.githubusercontent.com/6196971/184535348-c2887495-884f-423c-88ec-4564fe208223.mov

(

**Comment by MunifTanjim** [comment]
What to you see when you do:

- `:NullLsInfo`
- `:LspInfo`

Is `null-ls` attached to the buffer?

I can't know for sure what might be wrong without seeing your config.

Maybe open a new issue with all the details?

@dlvhdr

**Comment by dlvhdr** [comment]
cool I will! thanks for the help :)

**Comment by andresgutgon** [comment]
Hi, I'm having a similar issue. In my case I think is because `plugins` options in my Prettier config. 

```js
// .prettier.config.cjs
// With plugins .
/** @typedef  {import("@ianvs/prettier-plugin-sort-imports").PluginConfig} SortImportsConfig*/
/** @typedef  {import("prettier").Config} PrettierConfig*/
/** @typedef  {{ tailwindConfig: string }} TailwindConfig*/

/** @type { PrettierConfig | SortImportsConfig | TailwindConfig } */
const config = {
  arrowParens: 'always',
  printWidth: 80,
  singleQuote: true,
  jsxSingleQuote: true,
  semi: false,
  trailingComma: 'all',
  tabWidth: 2,
  // pluginSearchDirs: false,
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],
  tailwindConfig: './packages/tailwind-config/tailwind.config',
  importOrder: [
    '^(react/(.*)$)|^(react$)|^(react-native(.*)$)',
    '^(next/(.*)$)|^(next$)',
    '^(expo(.*)$)|^(expo$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^ui/(.*)$',
    '',
    '^~/utils/(.*)$',
    '^~/components/(.*)$',
    '^~/styles/(.*)$',
    '^~/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
}
```
☝️ This works fine by running `prettier` command with `npm run prettier`

But it doesn't work when I do `:w` in Neo Vim

But this file works with `:w` save
``` javascript
// .prettier.config.cjs
// With plugins .
/** @typedef  {import("@ianvs/prettier-plugin-sort-imports").PluginConfig} SortImportsConfig*/
/** @typedef  {import("prettier").Config} PrettierConfig*/
/** @typedef  {{ tailwindConfig: string }} TailwindConfig*/

/** @type { PrettierConfig | SortImportsConfig | TailwindConfig } */
const config = {
  arrowParens: 'always',
  printWidth: 80,
  singleQuote: true,
  jsxSingleQuote: true,
  semi: false,
  trailingComma: 'all',
  tabWidth: 2,
}
```

So removing the 2 plugins it works in Neo Vim

**Comment by MunifTanjim** [comment]
@andresgutgon

- Are you using `prettierd`? If yes
  - What's the version of `prettierd`?
  - Does it work when you directy execute `prettierd` from terminal?
- What's the output of `:NullLsInfo`?
- What's the output of `:LspInfo`?

**Comment by andresgutgon** [comment]
> Are you using prettierd?

No, `pnpm` installed `prettier` in the project.

`:LspInfo`
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/49499/232318928-823eb670-e9fd-4801-8f90-c92635c9f5c9.png">

`:NullLsInfo`
<img width="972" alt="image" src="https://user-images.githubusercontent.com/49499/232319044-92694c60-9333-47e7-a9f0-919dd46b020b.png">

**Comment by andresgutgon** [comment]
@MunifTanjim I hope this can help

**Comment by andresgutgon** [comment]
Without `plugins` and the rest of the attributes commented as [explained here](https://github.com/MunifTanjim/prettier.nvim/issues/9#issuecomment-1510314170) it works:



``` javascript
// .prettier.config.cjs
// With plugins .
/** @typedef  {import("@ianvs/prettier-plugin-sort-imports").PluginConfig} SortImportsConfig*/
/** @typedef  {import("prettier").Config} PrettierConfig*/
/** @typedef  {{ tailwindConfig: string }} TailwindConfig*/

/** @type { PrettierConfig | SortImportsConfig | TailwindConfig } */
const config = {
  arrowParens: 'always',
  printWidth: 80,
  singleQuote: true,
  jsxSingleQuote: true,
  semi: false,
  trailingComma: 'all',
  tabWidth: 2,
}
```
